In [1]:
from keras.models import load_model


In [4]:
model2 = load_model('BrainTumor_CNN.h5')

In [5]:
model2.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_31 (Conv2D)          (None, 50, 50, 6)         60        
                                                                 
 max_pooling2d_18 (MaxPooli  (None, 25, 25, 6)         0         
 ng2D)                                                           
                                                                 
 conv2d_32 (Conv2D)          (None, 13, 13, 6)         330       
                                                                 
 max_pooling2d_19 (MaxPooli  (None, 6, 6, 6)           0         
 ng2D)                                                           
                                                                 
 conv2d_33 (Conv2D)          (None, 3, 3, 6)           330       
                                                                 
 conv2d_34 (Conv2D)          (None, 2, 2, 7)          

In [6]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Create the Sequential model
model = Sequential()

# Add convolutional layers
model.add(Conv2D(3,19, (2, 2), activation='relu',stride=2, padding=(1,1), bias=False ,input_shape=(50, 50, 1)))
model.add(MaxPooling2D(pool_size=(2, 2),kernel_size=2, stride=2, ceil_mode=True))

model.add(Conv2D(6, (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(6, (3, 3), activation='relu'))
model.add(Conv2D(7, (2, 2), activation='relu'))

# Flatten layer
model.add(Flatten())

# Dense layers
model.add(Dense(84, activation='relu'))
model.add(Dense(70, activation='relu'))
model.add(Dense(10, activation='softmax'))  # Assuming 10 classes for output

# Print model summary
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 46, 46, 6)         156       
                                                                 
 max_pooling2d (MaxPooling2  (None, 23, 23, 6)         0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 6)         906       
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 9, 9, 6)           0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 7, 7, 6)           330       
                                                                 
 conv2d_3 (Conv2D)           (None, 6, 6, 7)           1

In [67]:
from keras.preprocessing.image import load_img, img_to_array, array_to_img
import numpy as np

# Load the image
input_image = load_img("photo.jpg")
input_image_array = img_to_array(input_image)
#print(input_image_array)
# Get the dimensions of the input image
rows, cols, channels = input_image_array.shape

print(rows,cols,channels)



1500 1000 3


In [84]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D,UpSampling2D, Conv2DTranspose
from keras.optimizers import Adam

input_image_array_2 = input_image_array.reshape(1, rows, cols, channels)
print(input_image_array_2)
def build_classifier(input_shape):
    def bm():
        classifier = Sequential() # initialize neural network
        # Convolutional layers
        classifier.add(Conv2D(3, kernel_size=(3,3),strides=(1, 1), input_shape=input_shape, activation='PReLU',padding='same'))
        #classifier.add(MaxPooling2D(pool_size=(2, 2)))
        
        classifier.add(Conv2D(35, kernel_size=(3,3),strides=(1, 1), activation='PReLU',padding='same'))
        #classifier.add(MaxPooling2D(pool_size=(2, 2)))
        
        classifier.add(Conv2D(35, kernel_size=(3,3),strides=(1, 1), activation='PReLU',padding='same'))
        classifier.add(MaxPooling2D(pool_size=(2, 2)))

        classifier.add(MaxPooling2D(pool_size=(2, 2)))

        classifier.add(UpSampling2D(size=(2, 2)))
        classifier.add(Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same',activation='PReLU'))

# Add PReLU activation
        # classifier.add(PReLU())
        
# Add another Deconvolutional (Conv2DTranspose) layer to upsample the feature maps
        classifier.add(Conv2DTranspose(32, (3, 3), strides=(1, 1), padding='same',activation='PReLU'))

# Add PReLU activation
        # model.add(PReLU())

# Add another Deconvolutional (Conv2DTranspose) layer to upsample the feature maps
        classifier.add(Conv2DTranspose(3, (3, 3), strides=(2, 2), padding='same', activation='sigmoid'))
        
        
        
        # # Flatten layer
        # classifier.add(Flatten())
        
        # Fully connected layers
        #classifier.add(Dense(units=80, activation='relu'))
        #classifier.add(Dense(units=448, activation='relu'))
    
    
        # Compile the model
        lr = 0.003
        adam0 = Adam(learning_rate=lr)
        classifier.compile(optimizer=adam0, loss='categorical_crossentropy', metrics=['accuracy'])
        

# Predict the output
        output_image =classifier.predict(input_image_array_2)
        print(output_image.shape[3])
# Convert output to image
        output_image = array_to_img(output_image[0])

# Save the output image
        output_image.save("converted.jpg")
        return classifier
    return bm

# Usage example



[[[[151. 171. 169.]
   [151. 171. 169.]
   [151. 171. 169.]
   ...
   [ 25.  20.  26.]
   [ 25.  20.  26.]
   [ 25.  20.  26.]]

  [[150. 170. 168.]
   [150. 170. 168.]
   [150. 170. 168.]
   ...
   [ 25.  20.  26.]
   [ 25.  20.  26.]
   [ 25.  20.  26.]]

  [[150. 170. 168.]
   [150. 170. 168.]
   [150. 170. 168.]
   ...
   [ 25.  20.  26.]
   [ 25.  20.  26.]
   [ 25.  20.  26.]]

  ...

  [[ 33.  31.  36.]
   [ 33.  31.  36.]
   [ 32.  30.  35.]
   ...
   [ 31.  29.  34.]
   [ 31.  29.  34.]
   [ 33.  31.  36.]]

  [[ 32.  30.  35.]
   [ 32.  30.  35.]
   [ 31.  29.  34.]
   ...
   [ 33.  31.  36.]
   [ 34.  32.  37.]
   [ 37.  35.  40.]]

  [[ 31.  29.  34.]
   [ 31.  29.  34.]
   [ 31.  29.  34.]
   ...
   [ 35.  33.  38.]
   [ 37.  35.  40.]
   [ 40.  38.  43.]]]]


In [85]:
input_shape = (rows, cols, channels)
classifier = build_classifier(input_shape)()
print("a",classifier)

1/1 [==============================] - 2s 2s/step
3
a <keras.src.engine.sequential.Sequential object at 0x000001D7EC96FBB0>


In [61]:
print(classifier.summary())

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_55 (Conv2D)          (None, 100, 100, 3)       30084     
                                                                 
 conv2d_56 (Conv2D)          (None, 100, 100, 35)      350980    
                                                                 
 conv2d_57 (Conv2D)          (None, 100, 100, 35)      361060    
                                                                 
 max_pooling2d_27 (MaxPooli  (None, 50, 50, 35)        0         
 ng2D)                                                           
                                                                 
 max_pooling2d_28 (MaxPooli  (None, 25, 25, 35)        0         
 ng2D)                                                           
                                                                 
 up_sampling2d_6 (UpSamplin  (None, 50, 50, 35)      